/* Generated by scripts/compile-smartcode.js — do not edit. */
export interface SmartCodeParams {
  accountId: string;
  settingsTimeout: number;
  hideElement: string;
  hideElementStyle: string;
}

const SMART_CODE_TEMPLATE = "window._wingify_code||function(){var e=__WINGIFY_ACCOUNT_ID__,t=__WINGIFY_SETTINGS_TIMEOUT__,n=window,i=document;if(!(-1<i.URL.indexOf(\"__wingify_disable__\")||n._wingify_code)){var _=!1,d=i.currentScript,o={sT:t,hES:\"__WINGIFY_HIDE_ELEMENT_STYLE__\",hE:\"__WINGIFY_HIDE_ELEMENT__\"};try{o=Object.assign(o,JSON.parse(localStorage.getItem(\"_wingify_\"+e+\"_config\")))}catch(o){}var c={script:d,nonce:d.nonce,settings_tolerance:function(){return o.sT},hide_element:function(){return performance.getEntriesByName(\"first-contentful-paint\")[0]?\"\":o.hE},hide_element_style:function(){return\"{\"+o.hES+\"}\"},getVersion:function(){return 3},finish:function(){var e;!_&&(_=!0,e=i.getElementById(\"_vis_opt_path_hides\"))&&e.parentNode.removeChild(e)},finished:function(){return _},addScript:function(e){var t=i.createElement(\"script\");t.src=e;d.nonce&&t.setAttribute(\"nonce\",d.nonce);t.fetchPriority=\"high\";i.head.appendChild(t)},init:function(){n._settings_timer=setTimeout((function(){c.finish()}),this.settings_tolerance());var t,_=this.hide_element();_&&((t=i.createElement(\"style\")).id=\"_vis_opt_path_hides\",d.nonce&&t.setAttribute(\"nonce\",d.nonce),t.textContent=_+this.hide_element_style(),i.head.appendChild(t));this.addScript(\"https://edge.wingify.net/tag/\"+e+\".js\")}};n._wingify_code=c;c.init()}}();function d(){var e;t._wingify_code&&(e=d.hidingStyle=document.getElementById(\"_vis_opt_path_hides\")||d.hidingStyle,t._wingify_code.finished()||_wingify_code.libExecuted||t.Wingify&&Wingify.dNR||!t._wingify_code.hide_element()||(document.getElementById(\"_vis_opt_path_hides\")||document.getElementsByTagName(\"head\")[0].appendChild(e),requestAnimationFrame(d)))}var t;t=window;d();";

export function buildSmartCode(p: SmartCodeParams): string {
  return SMART_CODE_TEMPLATE.replace(
    /__WINGIFY_ACCOUNT_ID__/g,
    p.accountId
  )
    .replace(/__WINGIFY_SETTINGS_TIMEOUT__/g, String(p.settingsTimeout))
    .replace(
      /["']__WINGIFY_HIDE_ELEMENT__["']/g,
      JSON.stringify(p.hideElement)
    )
    .replace(
      /["']__WINGIFY_HIDE_ELEMENT_STYLE__["']/g,
      JSON.stringify(p.hideElementStyle)
    );
}
